export { default as SwapiNavBar } from './SwapiNavBar'
export { default as SwapiTabView } from './SwapiTabView'
export { default as Swapiperson } from './SwapiPerson'
export { default as SwapiPlanet } from './SwapiPlanet'
export { default as SwapiSpecies } from './SwapiSpecies'
export { default as SwapiStarhip } from './SwapiStarship'
export { default as SwapiVehicle } from './SwapiVehicle'
export { default as SwapiFilm } from './SwapiFilm'
export { EasyTab, EasyTabs } from './EasyTabs/EasyTabs'